verbose: 3
optimization_movie: true
concatenate_xyz: true
overwrite_output_path: true
Output_Path: '../src14_Assembly_Unit_Test/DART_Example_Pd_Ni_Complexes_test_041023' #I have appended '_test_041023' so that I can test If the example is performing correctly
complex_name_length: 8

Batches:
  - Input_Path: '/Users/cianclarke/Documents/PhD/Complex_Assembly/DART/data/Filtered_Jsons/P_N_with_Benzene_Br/P_N_080823.json'
    Isomers: Generate All
    MAX_num_complexes: 10000
    Metal:
      element: Pd
      oxidation_state: 2
      spin: 1
    Name: P_N_Donors_Pd_Metal_Centre
    Optimisation_Choice: false
    Random_Seed: 0
    Topology: '(2, 1, 1)--(1, 2, 3)'
    Total_Charge: 0
    complex_name_appendix: _PN_Pd

  - Input_Path: '/Users/cianclarke/Documents/PhD/Complex_Assembly/DART/data/Filtered_Jsons/P_N_with_Benzene_Br/P_N_080823.json'
    Isomers: Generate All
    MAX_num_complexes: 10000
    Metal:
      element: Ni
      oxidation_state: 2
      spin: 1
    Name: P_N_Donors_Ni_Metal_Centre
    Optimisation_Choice: false
    Random_Seed: 0
    Topology: '(2, 1, 1)--(1, 2, 3)'
    Total_Charge: 0
    complex_name_appendix: _PN_Ni