name: DART
channels:
  - conda-forge
  - defaults
dependencies:
  - ase
  - jsonlines
  - networkx
  - numpy
  - openbabel
  - pandas
  - pbr                       # Needed for pysmiles, better to install now via conda then later via pip.
  - pip
  - python                    # DART was tested with python>=3.9, but it might be possible to use lower versions as well.
  - pyyaml
  - rdkit
  - scipy                     # scikit-learn Lasso fit with sparse matrices fails with scipy 1.11 so for ligand extraction it should be scipy<=1.10.1.
  - scikit-learn
  - stk
  - sympy
  - tqdm
  - pip:
      - pysmiles
      - -e .                  # Install DART in editable mode. All of its dependencies are installed by conda.
