# Conda environment for DART developers.
name: DART_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.16
  - apeye=1.4.1
  - apeye-core=1.1.5
  - ase=3.23.0
  - atomlite=4.4.5
  - attrs=23.2.0
  - autodocsumm=0.2.13
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blinker=1.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cachecontrol=0.14.0
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.1
  - cssutils=2.11.0
  - cycler=0.12.1
  - dict2css=0.3.0.post1
  - dill=0.3.8
  - dnspython=2.6.1
  - docutils=0.20.1
  - domdf-python-tools=3.9.0
  - expat=2.6.2
  - filelock=3.15.4
  - flask=3.0.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - freetype-py=2.3.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - greenlet=3.0.3
  - h2=4.1.0
  - hpack=4.0.0
  - html5lib=1.1
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.7
  - imagesize=1.4.1
  - importlib-metadata=8.2.0
  - importlib-resources=6.4.0
  - importlib_resources=6.4.0
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsonlines=4.0.0
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-python=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libdeflate=1.20
  - libedit=3.1.20230828
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.3
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libpq=16.3
  - librdkit=2024.03.5
  - libsqlite=3.46.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - markupsafe=2.1.5
  - matplotlib-base=3.9.1
  - mchammer=2024.2.29.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - natsort=8.4.0
  - ncurses=6.5
  - networkx=3.3
  - numpy=2.0.1
  - openbabel=3.1.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - pathos=0.3.2
  - patsy=0.5.6
  - pbr=6.0.0
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.1.2
  - pixman=0.43.4
  - platformdirs=4.2.2
  - polars=1.2.1
  - pox=0.3.4
  - ppft=1.7.6.8
  - pthread-stubs=0.4
  - pycairo=1.26.1
  - pycparser=2.22
  - pygments=2.18.0
  - pymongo=4.8.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - qhull=2020.2
  - rdkit=2024.03.5
  - readline=8.2
  - reportlab=4.2.2
  - requests=2.32.3
  - rlpycairo=0.2.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=67.1.0
  - six=1.16.0
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - soupsieve=2.5
  - sphinx=7.4.7
  - sphinx-autodoc-typehints=2.2.3
  - sphinx-jinja2-compat=0.2.0.post1
  - sphinx-prompt=1.4.0
  - sphinx-tabs=3.4.1
  - sphinx-toolbox=3.7.0
  - sphinx_rtd_theme=2.0.0
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - spindry=2024.2.29.0
  - sqlalchemy=2.0.31
  - statsmodels=0.14.2
  - stk=2024.3.28.0
  - sympy=1.13.0
  - tabulate=0.9.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tomli=2.0.1
  - tqdm=4.66.4
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - tzdata=2024a
  - urllib3=2.2.2
  - vabene=0.0.5
  - webencodings=0.5.1
  - werkzeug=3.0.3
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml=0.2.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - pysmiles==1.1.2
      - -e ../../.              # Install DART in editable mode without installing dependencies, these are handled by conda
